language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
install:
  - npm install -g snyk
  - npm install
  - snyk auth 2b219c46-9899-4ee5-bc48-3dce173ef7cc
  - snyk protect
after_success:
  - snyk monitor
branches:
  only:
  - master
deploy:
  provider: surge
  project: ./build
  skip_cleanup: true

after_deploy:
  - snyk monitor

